name: wasteapp
description: "Waste management application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.3
  equatable: ^2.0.7
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.4
  google_maps_flutter: ^2.10.1
  http: ^1.3.0
  image_picker: ^1.1.2
  location: ^8.0.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
